import json
import os
import random
import re
import subprocess
import smtplib
import sys
import time
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from zoneinfo import ZoneInfo

BASE      = os.path.dirname(os.path.abspath(__file__))   # repo root (Resume/)
SCAN_ROOT = os.path.dirname(BASE)                         # parent RR/ folder where .docx files live
JOB_LOG   = os.path.join(BASE, "job_log.json")
CONFIG    = os.path.join(BASE, "tracker_config.json")
GOAL      = 25
SCAN_LOG  = os.path.join(BASE, "scanned_files.json")
UK_TZ     = ZoneInfo("Europe/London")

# Keywords to classify role from filename (checked in order)
ROLE_KEYWORDS = {
    "da": ["data_analyst", "dataanalyst", "labour_model", "labourmodel",
           "data_transformation_analyst", "excel_data",
           "pricing_analyst", "market_pricing", "collections_analyst",
           "planning_analyst", "business_analyst", "insight_analyst",
           "operations_analyst", "commercial_analyst", "risk_analyst",
           "graduate_analyst", "junior_analyst"],
    "ds": ["data_scientist", "datascientist", "data_science", "datascience",
           "ds_ai", "_ds_", "quant_research", "quant_analyst",
           "applied_scientist", "research_scientist", "junior_research_scientist",
           "ml_evaluation"],
    "ml": ["ml_engineer", "ml_researcher", "ml_scientist", "applied_ml", "founding_ml",
           "deep_learning", "nlp_engineer", "computer_vision",
           "ml_research"],
    "ai": [
        "ai_engineer", "ai_developer", "ai_devloper", "ai_builder", "ai_specialist",
        "ai_solutions", "ai_creative", "ai_qa", "ai_researcher", "ai_research",
        "ai_platform", "ai_associate", "ai_operations", "ai_data", "applied_ai",
        "agentic_ai", "agenticai", "llm_engineer", "rag_engineer", "graduate_ai",
        "trainee_ai", "aiml_engineer", "aiml", "forward_deployed_ai", "generative_ai",
        "mle_agentic", "ai_intern", "numi_ai",
        "ai_architect", "ai_software", "ai_security", "ai_product", "ai_strategy",
        "datascience_specialist", "data_science_specialist",
        "software_ai", "founding_ai", "junior_ai", "senior_ai",
        "aiengineer", "aiengineering", "founding_engineer",
        # Extended AI keywords
        "gen_ai", "genai", "forward_deployed", "ai_analyst", "ai_automation",
        "ai_search", "solutions_architect", "ai_forward", "ai_consultant",
        "ai_pioneer", "ai_lead", "ai_principal", "ai_director",
    ],
    "se": [
        "software_engineer", "software_developer", "swengineer", "swe",
        "python_engineer", "python_software", "python_developer",
        "grad_swe", "graduate_software", "graduate_swe", "grad_se",
        "software_dev", "full_stack", "fullstack", "backend_engineer",
        "backend_developer", "graduate_se", "graduate_developer",
        "junior_developer", "junior_software", "junior_engineer",
        "analytics_developer", "cloud_ops", "cloudops",
        "graduate_swd", "software_graduate", "swd",
    ],
}
MLE_PATTERN = ["_mle", "mle_", "mle."]   # standalone MLE files → ml

# Cover-letter filename markers — not counted as applications
COVER_PATTERNS = ["cover_letter", "coverletter", "cover_ltr", "_cl_", "cl_resume"]

ROLES = {
    "ai": "AI / Generative AI Engineer",
    "da": "Data Analyst",
    "ds": "Data Scientist",
    "ml": "Machine Learning Engineer",
    "se": "Software / Other Engineer",
}

# All motivation and planning content is generated by the LLM based on live context.
# No static motivation lists — every email is unique to today's date, stats, and schedule.

# ─── UK time helpers ─────────────────────────────────────────────────────────

def now_uk():
    """Always return current UK time (BST in summer, GMT in winter)."""
    return datetime.now(UK_TZ)

def today():
    return now_uk().strftime("%Y-%m-%d")

def today_display():
    return now_uk().strftime("%A, %d %B %Y")

# ─── Data helpers ────────────────────────────────────────────────────────────

def load_log():
    if os.path.exists(JOB_LOG):
        with open(JOB_LOG, "r") as f:
            return json.load(f)
    return {}

def save_log(data):
    with open(JOB_LOG, "w") as f:
        json.dump(data, f, indent=2)

def load_config():
    cfg = {}
    if os.path.exists(CONFIG):
        with open(CONFIG, "r") as f:
            cfg = json.load(f)
    # GitHub Actions: override with environment variables (secrets)
    for env_key, cfg_key in [
        ("EMAIL_SENDER",   "email_sender"),
        ("EMAIL_PASSWORD", "email_password"),
        ("EMAIL_RECEIVER", "email_receiver"),
        ("GROQ_API_KEY", "groq_api_key"),
    ]:
        val = os.environ.get(env_key, "")
        if val:
            cfg[cfg_key] = val
    return cfg

def get_today_data():
    log = load_log()
    entry = log.get(today(), {})
    if isinstance(entry, int):
        entry = {"total": entry, "roles": {}}
    return entry

def get_today_total():
    d = get_today_data()
    return d.get("total", 0)

def add_application(role_key, n=1):
    log  = load_log()
    t    = today()
    if t not in log or isinstance(log[t], int):
        log[t] = {"total": 0, "roles": {r: 0 for r in ROLES}}
    log[t]["total"] = log[t].get("total", 0) + n
    log[t]["roles"][role_key] = log[t]["roles"].get(role_key, 0) + n
    save_log(log)
    return log[t]

def _normalize_fname(filename):
    """Lowercase + underscore, handling CamelCase (AppliedAI → applied_ai)."""
    name = re.sub(r'(?<=[a-z])(?=[A-Z])', '_', filename)
    return name.lower().replace("-", "_").replace(" ", "_")

def classify_role(filename):
    name = _normalize_fname(filename)
    # Cover letters are not standalone applications
    for pat in COVER_PATTERNS:
        if pat in name:
            return "other"
    # Role keyword matching
    for role in ("da", "ds", "ai", "ml", "se"):
        for kw in ROLE_KEYWORDS[role]:
            if kw in name:
                return role
    for kw in MLE_PATTERN:
        if kw in name:
            return "ml"
    # No keyword match — unclassified (will not be counted in job_log)
    return "other"

def load_scan_log():
    if os.path.exists(SCAN_LOG):
        with open(SCAN_LOG, "r") as f:
            return json.load(f)
    return {}

def save_scan_log(data):
    with open(SCAN_LOG, "w") as f:
        json.dump(data, f, indent=2)

def add_application_for_date(date_str, role_key, n=1):
    log = load_log()
    if date_str not in log or isinstance(log[date_str], int):
        log[date_str] = {"total": 0, "roles": {r: 0 for r in ROLES}}
    log[date_str]["total"] = log[date_str].get("total", 0) + n
    log[date_str]["roles"][role_key] = log[date_str]["roles"].get(role_key, 0) + n
    save_log(log)

def scan_and_log():
    """Walk SCAN_ROOT (parent dir), classify .docx files and log them.
    Skips the Resume/ subdir (tracker files). Re-classifies previously 'other' entries.
    """
    scan_log  = load_scan_log()
    new_files = []
    unknown   = []

    for root, dirs, files in os.walk(SCAN_ROOT):
        # Skip hidden dirs and the Resume/ subdir itself
        dirs[:] = [
            d for d in dirs
            if not d.startswith('.')
            and os.path.normcase(os.path.abspath(os.path.join(root, d))) !=
               os.path.normcase(os.path.abspath(BASE))
        ]
        for fname in files:
            if not fname.lower().endswith('.docx'):
                continue
            fpath    = os.path.join(root, fname)
            rel_path = os.path.relpath(fpath, SCAN_ROOT)

            # Skip files already properly classified (not "other")
            if rel_path in scan_log and scan_log[rel_path].get("role") != "other":
                continue

            role      = classify_role(fname)
            mtime     = os.path.getmtime(fpath)
            file_date = datetime.fromtimestamp(mtime, tz=UK_TZ).strftime("%Y-%m-%d")

            scan_log[rel_path] = {"role": role, "date": file_date}

            if role == "other":
                unknown.append(rel_path)
                continue

            # Check if this file was previously "other" (reclassified now)
            add_application_for_date(file_date, role)
            new_files.append((rel_path, role, file_date))

    save_scan_log(scan_log)

    # Summary
    role_counts = {r: 0 for r in ROLES}
    date_counts = {}
    for _, role, date in new_files:
        if role in role_counts:
            role_counts[role] += 1
        date_counts[date] = date_counts.get(date, 0) + 1

    print(f"\n{'='*60}")
    print(f"  SCAN COMPLETE — {len(new_files)} new files logged")
    print(f"{'='*60}")
    if new_files:
        print(f"\n  By Role:")
        for key, label in ROLES.items():
            if role_counts.get(key, 0):
                print(f"    {label:<35}: {role_counts[key]}")
        print(f"\n  By Date (most recent 5):")
        for date in sorted(date_counts)[-5:]:
            print(f"    {date}: {date_counts[date]} applications")
    if unknown:
        print(f"\n  Cover Letters / Unclassified ({len(unknown)} — not counted):")
        for p in unknown[:8]:
            print(f"    {os.path.basename(p)}")
        if len(unknown) > 8:
            print(f"    ... and {len(unknown)-8} more")
    print(f"{'='*60}\n")

    if new_files:
        auto_push_log()
    return new_files

def auto_push_log():
    """Silently commit and push job_log.json so GitHub Actions sees latest data."""
    try:
        subprocess.run(["git", "add", JOB_LOG], capture_output=True, cwd=BASE)
        result = subprocess.run(
            ["git", "commit", "-m", f"log: applications {today()}"],
            capture_output=True, cwd=BASE
        )
        if result.returncode == 0:
            subprocess.run(["git", "push", "origin", "main"], capture_output=True, cwd=BASE)
    except Exception:
        pass

# ─── Windows toast notification ───────────────────────────────────────────────

def toast(title, message):
    if sys.platform != "win32":
        return
    t = title.replace("'", "`'")
    m = message.replace("'", "`'")
    ps = f"""
Add-Type -AssemblyName System.Windows.Forms
$n = New-Object System.Windows.Forms.NotifyIcon
$n.Icon    = [System.Drawing.SystemIcons]::Information
$n.Visible = $true
$n.BalloonTipIcon  = 'Info'
$n.BalloonTipTitle = '{t}'
$n.BalloonTipText  = '{m}'
$n.ShowBalloonTip(9000)
Start-Sleep -Seconds 10
$n.Dispose()
"""
    subprocess.Popen(["powershell", "-WindowStyle", "Hidden", "-Command", ps])

# ─── Email builders ───────────────────────────────────────────────────────────

def _month_table_html():
    """HTML table of this month's applications by role, plus summary — included in every email."""
    log    = load_log()
    uk_now = now_uk()
    month_prefix = uk_now.strftime("%Y-%m")
    month_name   = uk_now.strftime("%B %Y")

    def _t(e):
        return e.get("total", 0) if isinstance(e, dict) else (e or 0)

    def _r(e, role):
        if isinstance(e, dict):
            return e.get("roles", {}).get(role, 0)
        return 0

    # collect and sort month entries
    rows = sorted(
        [(d, log[d]) for d in log if d.startswith(month_prefix)],
        key=lambda x: x[0]
    )
    if not rows:
        return ""

    role_keys   = list(ROLES.keys())
    role_labels = [ROLES[r].split()[0] for r in role_keys]   # first word: "AI", "Data"→"Data"...

    # shorter role column headers
    col_heads = ["AI", "DA", "DS", "ML", "SE"]

    th = "style='padding:6px 8px;font-size:11px;font-weight:bold;color:#fff;text-align:center;background:#1a5276;'"
    header_row = (
        f"<tr>"
        f"<th {th}>Date</th>"
        f"<th {th}>Total</th>"
        + "".join(f"<th {th}>{h}</th>" for h in col_heads) +
        f"</tr>"
    )

    # totals accumulators
    col_totals = {r: 0 for r in role_keys}
    grand = 0
    days_active = 0
    goal_days   = 0

    data_rows = ""
    for date_str, entry in rows:
        t = _t(entry)
        grand       += t
        days_active += 1 if t > 0 else 0
        goal_days   += 1 if t >= GOAL else 0
        for r in role_keys:
            col_totals[r] += _r(entry, r)

        day_label = date_str[8:]   # "01", "02", …
        if t >= GOAL:
            row_bg = "#eafaf1"
            total_color = "#1e8449"
        elif t == 0:
            row_bg = "#fdedec"
            total_color = "#c0392b"
        else:
            row_bg = "#fff"
            total_color = "#2c3e50"

        td  = f"style='padding:5px 8px;font-size:12px;text-align:center;border-bottom:1px solid #eee;color:#2c3e50;background:{row_bg};'"
        tdt = f"style='padding:5px 8px;font-size:12px;text-align:center;border-bottom:1px solid #eee;font-weight:bold;color:{total_color};background:{row_bg};'"
        data_rows += (
            f"<tr>"
            f"<td {td}>{day_label}</td>"
            f"<td {tdt}>{t}</td>"
            + "".join(f"<td {td}>{_r(entry, r) or '—'}</td>" for r in role_keys) +
            f"</tr>"
        )

    # summary / totals row
    tds = "style='padding:6px 8px;font-size:12px;font-weight:bold;text-align:center;background:#eaf4fb;color:#1a5276;border-top:2px solid #2980b9;'"
    totals_row = (
        f"<tr>"
        f"<td {tds}>Total</td>"
        f"<td {tds}>{grand}</td>"
        + "".join(f"<td {tds}>{col_totals[r]}</td>" for r in role_keys) +
        f"</tr>"
    )

    avg = round(grand / days_active, 1) if days_active else 0
    summary_line = (
        f"<p style='margin:10px 0 0;font-size:12px;color:#566573;'>"
        f"<b>{month_name}:</b> &nbsp;"
        f"{grand} applications &nbsp;&middot;&nbsp; "
        f"{days_active} active days &nbsp;&middot;&nbsp; "
        f"avg {avg}/day &nbsp;&middot;&nbsp; "
        f"goal hit {goal_days} days"
        f"</p>"
    )

    return (
        f"<tr><td style='padding:0 28px 24px;'>"
        f"<p style='margin:0 0 8px;font-size:12px;font-weight:bold;color:#1a5276;"
        f"text-transform:uppercase;letter-spacing:1.5px;'>{month_name} — Application Log</p>"
        f"<div style='overflow-x:auto;'>"
        f"<table width='100%' cellpadding='0' cellspacing='0' "
        f"style='border-collapse:collapse;border-radius:8px;overflow:hidden;'>"
        f"{header_row}{data_rows}{totals_row}"
        f"</table>"
        f"</div>"
        f"{summary_line}"
        f"</td></tr>"
    )


def _html_section(title, content, bg="#eaf4fb", border="#2980b9", title_color="#1a5276",
                   text_color="#2c3e50", padding="0 28px 20px"):
    """Reusable coloured card section for emails."""
    return (
        f"<tr><td style='padding:{padding};'>"
        f"<div style='background:{bg};border-left:5px solid {border};"
        f"border-radius:8px;padding:18px 20px;'>"
        f"<p style='margin:0 0 10px;font-size:12px;font-weight:bold;color:{title_color};"
        f"text-transform:uppercase;letter-spacing:1.5px;'>{title}</p>"
        f"<p style='margin:0;font-size:14px;color:{text_color};line-height:1.8;'>{content}</p>"
        f"</div></td></tr>"
    )

def _morning_stats():
    """Compact stats block for the 7 AM email: yesterday, today so far, week, all-time, streak."""
    from datetime import timedelta
    log     = load_log()
    uk_now  = now_uk()
    today_s = today()
    yest_s  = (uk_now - timedelta(days=1)).strftime("%Y-%m-%d")

    def _t(e):
        return e.get("total", 0) if isinstance(e, dict) else (e or 0)

    yest_entry  = log.get(yest_s, {})
    yest_total  = _t(yest_entry)
    yest_roles  = yest_entry.get("roles", {}) if isinstance(yest_entry, dict) else {}

    today_total = _t(log.get(today_s, {}))
    week_total  = sum(_t(log.get((uk_now - timedelta(days=i)).strftime("%Y-%m-%d"), {})) for i in range(7))
    grand_total = sum(_t(e) for e in log.values())

    streak = 0
    for i in range(len(log) + 1):
        d = (uk_now - timedelta(days=i)).strftime("%Y-%m-%d")
        if _t(log.get(d, {})) > 0:
            streak += 1
        else:
            break

    # Month-specific stats (current calendar month)
    month_prefix  = uk_now.strftime("%Y-%m")
    month_name    = uk_now.strftime("%B")
    month_entries = {d: e for d, e in log.items() if d.startswith(month_prefix)}
    month_totals  = [_t(e) for e in month_entries.values()]
    days_active   = sum(1 for t in month_totals if t > 0)
    month_total   = sum(month_totals)
    avg_per_day   = round(month_total / days_active, 1) if days_active else 0
    goal_hit      = sum(1 for t in month_totals if t >= GOAL)

    return {
        "yesterday_total": yest_total,
        "yesterday_roles": yest_roles,
        "today_so_far":    today_total,
        "week_total":      week_total,
        "grand_total":     grand_total,
        "streak":          streak,
        "month_name":      month_name,
        "days_active":     days_active,
        "avg_per_day":     avg_per_day,
        "goal_hit":        goal_hit,
    }


def build_morning_html(llm=None):
    applied    = get_today_total()
    data       = get_today_data()
    roles_data = data.get("roles", {r: 0 for r in ROLES})
    remaining  = max(0, GOAL - applied)
    stats      = _morning_stats()
    if llm is None:
        llm = generate_llm_content("morning", applied, roles_data, remaining)

    if llm:
        headline   = llm.get("headline", "Good Morning — Time to Dominate")
        motivation = llm.get("motivation", "")
        plan       = llm.get("plan", "")
    else:
        headline   = f"Good Morning, Raju — Goal: {GOAL} Today"
        motivation = ""
        plan       = ""

    color    = "#1a5276"
    date_str = today_display()

    # ── Stats block ──────────────────────────────────────────────────────────
    yest_total   = stats["yesterday_total"]
    yest_roles   = stats["yesterday_roles"]
    today_so_far = stats["today_so_far"]
    week_total   = stats["week_total"]
    grand_total  = stats["grand_total"]
    streak      = stats["streak"]
    month_name  = stats["month_name"]
    days_active = stats["days_active"]
    avg_per_day = stats["avg_per_day"]
    goal_hit    = stats["goal_hit"]

    yest_role_str = " &nbsp;|&nbsp; ".join(
        f"{k.upper()}: {yest_roles.get(k, 0)}"
        for k in ROLES if yest_roles.get(k, 0) > 0
    ) or "—"

    streak_html = (
        f" &nbsp;<span style='background:#27ae60;color:#fff;padding:2px 8px;border-radius:12px;"
        f"font-size:11px;font-weight:bold;'>{streak}-day streak</span>"
        if streak > 1 else ""
    )

    def _stat_cell(label, val, border=True):
        bdr = "border-right:1px solid #dde;" if border else ""
        return (
            f"<td style='text-align:center;padding:12px 8px;{bdr}'>"
            f"<div style='font-size:22px;font-weight:bold;color:#1a5276;'>{val}</div>"
            f"<div style='font-size:10px;color:#7f8c8d;text-transform:uppercase;"
            f"letter-spacing:1px;margin-top:3px;'>{label}</div>"
            f"</td>"
        )

    row1 = (
        _stat_cell("Yesterday",    yest_total) +
        _stat_cell("Today so far", today_so_far) +
        _stat_cell("This week",    week_total) +
        _stat_cell("All-time",     grand_total, border=False)
    )
    row2 = (
        _stat_cell(f"{month_name} active",   days_active) +
        _stat_cell(f"{month_name} avg/day",  avg_per_day) +
        _stat_cell(f"{month_name} goal hit", f"{goal_hit} days", border=False)
    )

    stats_block = (
        f"<tr><td style='padding:0 28px 20px;'>"
        f"<div style='background:#f4f6fb;border-radius:10px;padding:4px;border:1px solid #e0e4ed;'>"
        f"<table width='100%' cellpadding='0' cellspacing='0'>"
        f"<tr>{row1}</tr>"
        f"<tr style='border-top:1px solid #dde;'>{row2}</tr>"
        f"</table>"
        f"</div>"
        f"<p style='margin:8px 4px 0;font-size:12px;color:#566573;'>"
        f"Yesterday by role: <b>{yest_role_str}</b>{streak_html}</p>"
        f"</td></tr>"
    )

    motivation_block = (
        f"<tr><td style='padding:0 28px 18px;'>"
        f"<p style='font-size:15px;color:#2c3e50;line-height:1.9;margin:0;'>{motivation}</p>"
        f"</td></tr>"
    ) if motivation else ""

    plan_block = _html_section(
        "Today's Game Plan",
        plan,
        bg="#eaf4fb", border="#2980b9", title_color="#1a5276"
    ) if plan else ""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset='UTF-8'></head>
<body style='margin:0;padding:0;background:#f0f3f7;font-family:Arial,sans-serif;'>
<table width='100%' cellpadding='0' cellspacing='0'
       style='max-width:620px;margin:30px auto;background:#fff;border-radius:14px;
              overflow:hidden;box-shadow:0 6px 30px rgba(0,0,0,0.13);'>

  <tr><td style='background:{color};padding:38px 28px 30px;text-align:center;'>
    <p style='color:#aed6f1;margin:0 0 8px;font-size:12px;letter-spacing:2.5px;text-transform:uppercase;'>
      Good Morning, Raju &nbsp;&middot;&nbsp; {date_str}
    </p>
    <h1 style='color:#fff;margin:0;font-size:28px;line-height:1.3;font-weight:800;'>{headline}</h1>
  </td></tr>

  {stats_block}
  {motivation_block}
  {plan_block}

  <tr><td style='padding:4px 28px 24px;'>
    <div style='background:linear-gradient(135deg,{color},#2980b9);border-radius:12px;
                padding:18px;text-align:center;'>
      <p style='color:#fff;margin:0;font-size:22px;font-weight:bold;'>
        GOAL: {GOAL} APPLICATIONS TODAY
      </p>
      <p style='color:#d6eaf8;margin:6px 0 0;font-size:13px;'>
        {remaining} remaining &nbsp;&middot;&nbsp; AI &nbsp;&middot;&nbsp; DA &nbsp;&middot;&nbsp; DS &nbsp;&middot;&nbsp; ML &nbsp;&middot;&nbsp; SE
      </p>
    </div>
  </td></tr>

  {_month_table_html()}

  <tr><td style='background:#f8f9fa;padding:16px 28px;text-align:center;'>
    <p style='margin:0;font-size:12px;color:#7f8c8d;'>
      Resume Tracker &nbsp;&middot;&nbsp; Baddela Raju &nbsp;&middot;&nbsp; Wimbledon, London
    </p>
  </td></tr>

</table>
</body>
</html>
"""

def build_midday_html(applied, roles_data, label_time="12:00 PM"):
    remaining  = max(0, GOAL - applied)
    pct        = min(100, int(applied / GOAL * 100))
    is_goal    = applied >= GOAL
    bar_color  = "#27ae60" if is_goal else "#e67e22" if pct >= 50 else "#e74c3c"
    date_str   = today_display()
    is_midnight = label_time == "12:00 AM"
    email_kind  = "midnight" if is_midnight else "midday"

    if is_goal:
        header_bg  = "#145a32"
        header_txt = f"GOAL CRUSHED — {applied}/{GOAL}!"
        sub_txt    = f"You hit the target &middot; {label_time} UK"
    elif applied >= 15:
        header_bg  = "#1a5276"
        header_txt = f"{applied}/{GOAL} — Strong Progress"
        sub_txt    = f"{label_time} UK &middot; {date_str}"
    elif applied >= 5:
        header_bg  = "#784212"
        header_txt = f"{applied}/{GOAL} — Push Required"
        sub_txt    = f"{label_time} UK &middot; {date_str}"
    else:
        header_bg  = "#922b21"
        header_txt = f"{applied}/{GOAL} — Urgent Alert"
        sub_txt    = f"{label_time} UK &middot; {date_str}"

    # Default fallback text (overridden by LLM below)
    if is_goal:
        main_color = "#27ae60"
        main_title = "Goal Achieved — Outstanding Discipline!"
        main_body  = (f"You applied to <b>{applied} jobs</b> today and crushed the {GOAL}-application goal. "
                      "This is the level of consistency that lands offers.")
    elif applied >= 15:
        main_color = "#e67e22"
        main_title = "Strong Day — Close It Out!"
        main_body  = (f"<b>{applied} applications</b> done, {remaining} more to reach {GOAL}. "
                      "One focused hour will close the gap.")
    elif applied >= 5:
        main_color = "#c0392b"
        main_title = "Push Harder Now!"
        main_body  = (f"<b>{applied} applications</b> so far — you need {remaining} more. "
                      "Close all distractions and apply relentlessly.")
    else:
        main_color = "#922b21"
        main_title = f"{'Zero' if applied == 0 else applied} Applications — Act Now!"
        main_body  = ("Your dream job will not find you. Set a 60-minute timer and apply to at least 10 jobs right now.")

    llm = generate_llm_content(email_kind, applied, roles_data, remaining)

    if llm:
        main_title = llm.get("headline", main_title)
        main_body  = llm.get("body", main_body)

    roles_rows = ""
    for key, label in ROLES.items():
        count = roles_data.get(key, 0)
        bar_w = min(100, int(count / max(applied, 1) * 100)) if applied else 0
        roles_rows += (
            f"<tr><td style='padding:10px 16px;border-bottom:1px solid #eee;font-size:14px;'>{label}</td>"
            f"<td style='padding:10px 16px;border-bottom:1px solid #eee;'>"
            f"<div style='display:flex;align-items:center;gap:8px;'>"
            f"<div style='flex:1;background:#ecf0f1;border-radius:20px;height:8px;'>"
            f"<div style='width:{bar_w}%;background:{bar_color};height:100%;border-radius:20px;'></div></div>"
            f"<span style='font-weight:bold;color:#2c3e50;min-width:20px;'>{count}</span>"
            f"</div></td></tr>"
        )

    # ── MIDDAY-specific sections ──────────────────────────────────────────
    if not is_midnight and llm:
        half_verdict  = llm.get("half_time_verdict", "")
        aft_plan      = llm.get("afternoon_battle_plan", "")
        role_gap_fix  = llm.get("role_gap_fix", "")
        personal_edge = llm.get("personal_edge", "")

        extra_sections = "".join(filter(None, [
            _html_section("Half-Time Verdict", half_verdict,
                          bg="#fff8f0", border="#e67e22", title_color="#d35400",
                          padding="0 24px 16px") if half_verdict else "",
            _html_section("Afternoon Battle Plan", aft_plan,
                          bg="#eafaf1", border="#27ae60", title_color="#1e8449",
                          padding="0 24px 16px") if aft_plan else "",
            _html_section("Role Gap — Fix It Now", role_gap_fix,
                          bg="#fef9e7", border="#f39c12", title_color="#d68910",
                          padding="0 24px 16px") if role_gap_fix else "",
            _html_section("Your Personal Edge This Afternoon", personal_edge,
                          bg="#f5eef8", border="#8e44ad", title_color="#6c3483",
                          padding="0 24px 24px") if personal_edge else "",
        ]))

    # ── MIDNIGHT-specific sections ────────────────────────────────────────
    elif is_midnight and llm:
        day_verdict     = llm.get("day_verdict", "")
        perf_context    = llm.get("performance_context", "")
        tmrw_plan       = llm.get("tomorrow_battle_plan", "")
        skill_weapon    = llm.get("skill_weapon", "")
        mindset_reset   = llm.get("mindset_reset", "")

        extra_sections = "".join(filter(None, [
            _html_section("Day Verdict", day_verdict,
                          bg="#fff8f0", border="#e67e22", title_color="#d35400",
                          padding="0 24px 16px") if day_verdict else "",
            _html_section("Performance Context", perf_context,
                          bg="#eaf4fb", border="#2980b9", title_color="#1a5276",
                          padding="0 24px 16px") if perf_context else "",
            (
                "<tr><td style='padding:0 24px 16px;'>"
                "<div style='background:#eafaf1;border-left:5px solid #27ae60;"
                "border-radius:8px;padding:18px 20px;'>"
                "<p style='margin:0 0 10px;font-size:12px;font-weight:bold;color:#1e8449;"
                "text-transform:uppercase;letter-spacing:1.5px;'>Tomorrow's Battle Plan</p>"
                f"<p style='margin:0;font-size:14px;color:#2c3e50;line-height:1.9;'>{tmrw_plan}</p>"
                "</div></td></tr>"
            ) if tmrw_plan else "",
            (
                "<tr><td style='padding:0 24px 16px;'>"
                "<div style='background:linear-gradient(135deg,#1a5276,#6e2f8c);"
                "border-radius:10px;padding:20px 24px;'>"
                "<p style='margin:0 0 10px;font-size:12px;font-weight:bold;color:#aed6f1;"
                "text-transform:uppercase;letter-spacing:1.5px;'>Skill Weapon for Tomorrow</p>"
                f"<p style='margin:0;font-size:14px;color:#fff;line-height:1.9;'>{skill_weapon}</p>"
                "</div></td></tr>"
            ) if skill_weapon else "",
            _html_section("Mindset Reset", mindset_reset,
                          bg="#f5eef8", border="#8e44ad", title_color="#6c3483",
                          padding="0 24px 24px") if mindset_reset else "",
        ]))
    else:
        extra_sections = ""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset='UTF-8'></head>
<body style='margin:0;padding:0;background:#f0f3f7;font-family:Arial,sans-serif;'>
<table width='100%' cellpadding='0' cellspacing='0'
       style='max-width:620px;margin:30px auto;background:#fff;border-radius:14px;
              overflow:hidden;box-shadow:0 6px 30px rgba(0,0,0,0.12);'>

  <tr><td style='background:{header_bg};padding:30px 28px;text-align:center;'>
    <p style='color:#aed6f1;margin:0 0 6px;font-size:12px;letter-spacing:2.5px;text-transform:uppercase;'>
      {'End of Day' if is_midnight else 'Midday Check'} &nbsp;&middot;&nbsp; {date_str}
    </p>
    <h1 style='color:#fff;margin:0;font-size:24px;font-weight:800;'>{header_txt}</h1>
    <p style='color:#aed6f1;margin:8px 0 0;font-size:14px;'>{sub_txt}</p>
  </td></tr>

  <tr><td style='padding:24px 28px 10px;'>
    <p style='margin:0 0 8px;font-size:13px;color:#7f8c8d;font-weight:bold;
              text-transform:uppercase;letter-spacing:1px;'>Daily Progress</p>
    <div style='background:#ecf0f1;border-radius:50px;height:24px;overflow:hidden;'>
      <div style='width:{pct}%;background:{bar_color};height:100%;border-radius:50px;'></div>
    </div>
    <p style='margin:8px 0 0;font-size:13px;color:{bar_color};font-weight:bold;'>
      {applied}/{GOAL} ({pct}%)
      {'&nbsp;— GOAL MET!' if is_goal else f'&nbsp;— {remaining} more to reach {GOAL}'}
    </p>
  </td></tr>

  <tr><td style='padding:14px 28px 20px;'>
    <p style='margin:0 0 12px;font-size:13px;font-weight:bold;color:#2c3e50;
              text-transform:uppercase;letter-spacing:1px;'>Applications by Role</p>
    <table width='100%' style='border-collapse:collapse;border:1px solid #eee;border-radius:8px;overflow:hidden;'>
      <tr style='background:#2c3e50;'>
        <th style='padding:10px 16px;color:#fff;text-align:left;font-size:13px;'>Role</th>
        <th style='padding:10px 16px;color:#fff;text-align:left;font-size:13px;'>Progress</th>
      </tr>
      {roles_rows}
      <tr style='background:#f0f3f7;'>
        <td style='padding:12px 16px;font-weight:bold;font-size:15px;color:#2c3e50;'>Total</td>
        <td style='padding:12px 16px;font-weight:bold;font-size:22px;color:{bar_color};'>{applied}</td>
      </tr>
    </table>
  </td></tr>

  <tr><td style='padding:4px 28px 16px;'>
    <div style='background:{main_color}15;border-left:5px solid {main_color};
                border-radius:10px;padding:22px 24px;'>
      <p style='margin:0 0 12px;font-size:20px;font-weight:bold;color:{main_color};line-height:1.3;'>
        {main_title}
      </p>
      <p style='margin:0;font-size:15px;color:#2c3e50;line-height:1.9;'>
        {main_body}
      </p>
    </div>
  </td></tr>

  {extra_sections}

  {_month_table_html()}

</table>
<p style='text-align:center;font-size:11px;color:#bbb;margin-top:14px;'>
  Job Application Tracker &nbsp;&middot;&nbsp; Baddela Raju &nbsp;&middot;&nbsp; {date_str}
</p>
</body></html>
"""

def build_html(applied, goal, roles_data, is_goal_met):
    remaining  = max(0, goal - applied)
    pct        = min(100, int(applied / goal * 100))
    bar_color  = "#27ae60" if is_goal_met else "#e67e22" if pct >= 50 else "#e74c3c"
    now_str    = now_uk().strftime("%I:%M %p")
    date_str   = today_display()

    if is_goal_met:
        header_bg   = "#145a32"
        header_txt  = f"GOAL CRUSHED — {applied}/{goal} Today!"
        sub_txt     = f"{now_str} UK &middot; Outstanding!"
        cta_color   = "#27ae60"
        cta_default = "You hit 25+ applications today. That discipline is rare — keep it going tomorrow."
    elif applied == 0:
        header_bg   = "#922b21"
        header_txt  = f"0/{goal} — Get Started NOW"
        sub_txt     = f"{now_str} UK &middot; {date_str}"
        cta_color   = "#e74c3c"
        cta_default = "Not a single application yet. Set a 30-minute timer and apply to 5 jobs right now — just start."
    else:
        header_bg   = "#1a5276"
        header_txt  = f"{applied}/{goal} Done — {remaining} More to Go"
        sub_txt     = f"{now_str} UK &middot; {date_str}"
        cta_color   = "#e67e22"
        cta_default = f"{applied} applications done. {remaining} more will get you to the goal. One focused hour."

    llm             = generate_llm_content("check", applied, roles_data, remaining)
    llm_headline    = cta_default
    llm_body        = ""
    momentum_read   = ""
    action_sprint   = ""
    role_gap        = ""

    if llm:
        llm_headline  = llm.get("headline", cta_default)
        llm_body      = llm.get("body", "")
        momentum_read = llm.get("momentum_read", "")
        action_sprint = llm.get("action_sprint", "")
        role_gap      = llm.get("role_gap_analysis", "")

    roles_rows = ""
    for key, label in ROLES.items():
        count = roles_data.get(key, 0)
        bar_w = min(100, int(count / max(applied, 1) * 100)) if applied else 0
        roles_rows += (
            f"<tr><td style='padding:10px 16px;border-bottom:1px solid #eee;font-size:14px;'>{label}</td>"
            f"<td style='padding:10px 16px;border-bottom:1px solid #eee;'>"
            f"<div style='display:flex;align-items:center;gap:8px;'>"
            f"<div style='flex:1;background:#ecf0f1;border-radius:20px;height:8px;'>"
            f"<div style='width:{bar_w}%;background:{bar_color};height:100%;border-radius:20px;'></div></div>"
            f"<span style='font-weight:bold;color:#2c3e50;min-width:20px;'>{count}</span>"
            f"</div></td></tr>"
        )

    return f"""<!DOCTYPE html>
<html>
<head><meta charset='UTF-8'></head>
<body style='margin:0;padding:0;background:#f0f3f7;font-family:Arial,sans-serif;'>
<table width='100%' cellpadding='0' cellspacing='0'
       style='max-width:620px;margin:30px auto;background:#fff;border-radius:14px;
              overflow:hidden;box-shadow:0 6px 30px rgba(0,0,0,0.12);'>

  <tr><td style='background:{header_bg};padding:30px 28px;text-align:center;'>
    <p style='color:#aed6f1;margin:0 0 6px;font-size:12px;letter-spacing:2.5px;text-transform:uppercase;'>
      Progress Check &nbsp;&middot;&nbsp; {date_str}
    </p>
    <h1 style='color:#fff;margin:0;font-size:24px;font-weight:800;'>{header_txt}</h1>
    <p style='color:#aed6f1;margin:8px 0 0;font-size:14px;'>{sub_txt}</p>
  </td></tr>

  <tr><td style='padding:24px 28px 10px;'>
    <p style='margin:0 0 8px;font-size:13px;color:#7f8c8d;font-weight:bold;
              text-transform:uppercase;letter-spacing:1px;'>Daily Progress</p>
    <div style='background:#ecf0f1;border-radius:50px;height:24px;overflow:hidden;'>
      <div style='width:{pct}%;background:{bar_color};height:100%;border-radius:50px;'></div>
    </div>
    <p style='margin:8px 0 0;font-size:13px;color:{bar_color};font-weight:bold;'>
      {applied}/{goal} ({pct}%)
      {'&nbsp;— GOAL MET!' if is_goal_met else f'&nbsp;— {remaining} more to go'}
    </p>
  </td></tr>

  <tr><td style='padding:14px 28px 20px;'>
    <p style='margin:0 0 12px;font-size:13px;font-weight:bold;color:#2c3e50;
              text-transform:uppercase;letter-spacing:1px;'>By Role</p>
    <table width='100%' style='border-collapse:collapse;border:1px solid #eee;border-radius:8px;overflow:hidden;'>
      <tr style='background:#2c3e50;'>
        <th style='padding:10px 16px;color:#fff;text-align:left;font-size:13px;'>Role</th>
        <th style='padding:10px 16px;color:#fff;text-align:left;font-size:13px;'>Progress</th>
      </tr>
      {roles_rows}
    </table>
  </td></tr>

  <tr><td style='padding:4px 28px 16px;'>
    <div style='background:{cta_color}15;border-left:5px solid {cta_color};
                border-radius:10px;padding:22px 24px;'>
      <p style='margin:0 0 10px;font-size:18px;font-weight:bold;color:{cta_color};'>{llm_headline}</p>
      <p style='margin:0;font-size:14px;color:#2c3e50;line-height:1.9;'>{llm_body if llm_body else cta_default}</p>
    </div>
  </td></tr>

  {_html_section("Momentum Read", momentum_read,
     bg="#eaf4fb", border="#2980b9", title_color="#1a5276",
     padding="0 28px 16px") if momentum_read else ""}

  {_html_section("90-Minute Action Sprint", action_sprint,
     bg="#eafaf1", border="#27ae60", title_color="#1e8449",
     padding="0 28px 16px") if action_sprint else ""}

  {_html_section("Role Gap — Fix It", role_gap,
     bg="#fef9e7", border="#f39c12", title_color="#d68910",
     padding="0 28px 24px") if role_gap else ""}

  {_month_table_html()}

</table>
<p style='text-align:center;font-size:11px;color:#bbb;margin-top:14px;'>
  Job Application Tracker &nbsp;&middot;&nbsp; Baddela Raju &nbsp;&middot;&nbsp; {date_str}
</p>
</body></html>
"""

# ─── Email sender ─────────────────────────────────────────────────────────────

def send_email_raw(subject, html_body):
    cfg      = load_config()
    sender   = cfg.get("email_sender", "")
    password = cfg.get("email_password", "")
    receiver = cfg.get("email_receiver", "rajubaddela1234@gmail.com")

    if not sender or not password:
        print("Email not configured. Run: python resume_tracker.py setup")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = sender
        msg["To"]      = receiver
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as srv:
            srv.login(sender, password)
            srv.sendmail(sender, receiver, msg.as_string())
        print(f"Email sent to {receiver}")
        return True
    except Exception as e:
        print(f"Email failed: {e}")
        return False

def send_email(subject, applied, roles_data, is_goal_met):
    html = build_html(applied, GOAL, roles_data, is_goal_met)
    send_email_raw(subject, html)

# ─── 7 AM — Morning motivation ────────────────────────────────────────────────

def morning_motivate():
    date_str  = today_display()
    stats     = _morning_stats()

    # Build the email first — LLM runs inside build_morning_html()
    applied    = get_today_total()
    data       = get_today_data()
    roles_data = data.get("roles", {r: 0 for r in ROLES})
    remaining  = max(0, GOAL - applied)
    llm        = generate_llm_content("morning", applied, roles_data, remaining)

    headline = (llm.get("headline", "") if llm else "") or f"Goal: {GOAL} Applications — Let's Go"
    subject  = f"Good Morning, Raju — {headline} | {date_str}"

    toast(
        "Good Morning, Raju!",
        f"Yesterday: {stats['yesterday_total']} apps | Today goal: {GOAL} | {headline}"
    )

    html = build_morning_html(llm=llm)
    send_email_raw(subject, html)

    print(f"\n{'='*55}")
    print(f"  7 AM MORNING EMAIL (UK time)")
    print(f"  {date_str}")
    print(f"  Headline    : {headline}")
    print(f"  Yesterday   : {stats['yesterday_total']} applications")
    print(f"  Today so far: {stats['today_so_far']} applications")
    print(f"  All-time    : {stats['grand_total']} applications")
    print(f"  Streak      : {stats['streak']} day(s)")
    print(f"  Goal today  : {GOAL}")
    print(f"{'='*55}\n")

# ─── 12 PM — Midday check ────────────────────────────────────────────────────

def midday_check():
    data       = get_today_data()
    applied    = data.get("total", 0)
    roles_data = data.get("roles", {r: 0 for r in ROLES})
    remaining  = GOAL - applied
    is_goal    = applied >= GOAL
    date_str   = today_display()

    if is_goal:
        subject = f"Midday — GOAL MET! {applied}/{GOAL} Applications | {date_str}"
        t_title = f"Midday Check: GOAL MET — {applied}/{GOAL}!"
        t_msg   = "You crushed the goal before noon! Outstanding work today, Raju!"
    elif applied == 0:
        subject = f"Midday Alert — 0/{GOAL} Applications Yet! | {date_str}"
        t_title = "Midday Alert: 0 Applications!"
        t_msg   = f"It's noon UK time and you haven't started! {GOAL} applications needed — go NOW!"
    else:
        subject = f"12 PM UK — {applied}/{GOAL} Done, {remaining} More Needed | {date_str}"
        t_title = f"Midday: {applied}/{GOAL} Applications"
        role_summary = " | ".join(f"{k.upper()}={roles_data.get(k,0)}" for k in ROLES)
        t_msg   = f"{applied} done, {remaining} to go this afternoon! {role_summary}"

    toast(t_title, t_msg)
    html = build_midday_html(applied, roles_data)
    send_email_raw(subject, html)

    print(f"\n{'='*55}")
    print(f"  12 PM MIDDAY CHECK (UK time)")
    print(f"  Date    : {date_str}")
    print(f"  Applied : {applied}/{GOAL}")
    print(f"  Status  : {'GOAL MET!' if is_goal else f'{remaining} remaining this afternoon'}")
    for key, label in ROLES.items():
        print(f"  {label:<35}: {roles_data.get(key, 0)}")
    print(f"{'='*55}\n")

# ─── 12 AM — Midnight final summary ──────────────────────────────────────────

def midnight_summary():
    data       = get_today_data()
    applied    = data.get("total", 0)
    roles_data = data.get("roles", {r: 0 for r in ROLES})
    remaining  = GOAL - applied
    is_goal    = applied >= GOAL
    date_str   = today_display()

    if is_goal:
        subject = f"Day Complete — GOAL CRUSHED! {applied}/{GOAL} Applications | {date_str}"
        t_title = f"Day Done: GOAL CRUSHED — {applied}/{GOAL}!"
        t_msg   = "You finished the day strong! Outstanding work, Raju!"
    elif applied >= 15:
        subject = f"Day Wrap-Up — {applied}/{GOAL} Applications | {date_str}"
        t_title = f"Day Done: {applied}/{GOAL} — Great effort!"
        t_msg   = f"{applied} applications today. {remaining} short of goal — push harder tomorrow!"
    elif applied >= 5:
        subject = f"Day Wrap-Up — {applied}/{GOAL} Applications | {date_str}"
        t_title = f"Day Done: {applied}/{GOAL} — Need more tomorrow"
        t_msg   = f"Only {applied} applications today. Tomorrow: start early, apply harder!"
    else:
        subject = f"Day Wrap-Up — Only {applied}/{GOAL} Applications | {date_str}"
        t_title = f"Day Done: {applied}/{GOAL} — Not enough!"
        t_msg   = f"{'Zero' if applied == 0 else applied} applications today. Tomorrow is a fresh start — make it count!"

    toast(t_title, t_msg)
    html = build_midday_html(applied, roles_data, label_time="12:00 AM")
    send_email_raw(subject, html)

    print(f"\n{'='*55}")
    print(f"  12 AM MIDNIGHT FINAL SUMMARY (UK time)")
    print(f"  Date    : {date_str}")
    print(f"  Applied : {applied}/{GOAL}")
    print(f"  Status  : {'GOAL MET!' if is_goal else f'{remaining} short of goal'}")
    for key, label in ROLES.items():
        print(f"  {label:<35}: {roles_data.get(key, 0)}")
    print(f"{'='*55}\n")

# ─── Core check ───────────────────────────────────────────────────────────────

def check_and_notify():
    data       = get_today_data()
    applied    = data.get("total", 0)
    roles_data = data.get("roles", {r: 0 for r in ROLES})
    remaining  = GOAL - applied
    is_goal    = applied >= GOAL
    hour       = now_uk().hour

    if is_goal:
        title   = f"GOAL CRUSHED! {applied}/{GOAL} Jobs Applied Today!"
        message = "You're unstoppable! 25+ applications done. Keep the momentum tomorrow!"
        subject = f"GOAL ACHIEVED — {applied}/{GOAL} Applications | {today_display()}"
    elif applied == 0 and hour >= 10:
        title   = "URGENT: 0 Applications Yet Today!"
        message = f"You haven't started! 0/{GOAL} jobs applied. Get going NOW — every application counts."
        subject = f"0/{GOAL} Applications Today — Start NOW! | {today_display()}"
    elif applied == 0:
        title   = f"Good Morning! Time to Apply — Goal: {GOAL} Jobs Today"
        message = f"Start your day strong — apply to {GOAL} jobs across AI, DA, DS, ML, SE roles."
        subject = f"Morning Push — 0/{GOAL} Applications | {today_display()}"
    else:
        title   = f"Job Tracker: {applied}/{GOAL} Applied — {remaining} More Needed!"
        role_summary = " | ".join(f"{k.upper()}={roles_data.get(k,0)}" for k in ROLES)
        message = f"{applied} done, {remaining} to go! {role_summary}"
        subject = f"{applied}/{GOAL} Applications Today — {remaining} More To Go! | {today_display()}"

    toast(title, message)
    send_email(subject, applied, roles_data, is_goal)
    print(f"\n{'='*50}")
    print(f"  Date    : {today_display()} (UK time)")
    print(f"  Applied : {applied}/{GOAL}")
    print(f"  Status  : {'GOAL MET!' if is_goal else f'{remaining} remaining'}")
    for key, label in ROLES.items():
        print(f"  {label:<35}: {roles_data.get(key, 0)}")
    print(f"{'='*50}\n")

# ─── Summary ──────────────────────────────────────────────────────────────────

def show_summary():
    log = load_log()
    print(f"\n{'='*70}")
    print(f"  JOB APPLICATION TRACKER — BADDELA RAJU")
    print(f"{'='*70}")
    if not log:
        print("  No data yet. Start logging with: python resume_tracker.py add ai 3")
        return
    grand_total = 0
    goal_days   = 0
    role_totals = {r: 0 for r in ROLES}
    for date in sorted(log):
        entry = log[date]
        if isinstance(entry, int):
            total = entry
            roles = {}
        else:
            total = entry.get("total", 0)
            roles = entry.get("roles", {})
        grand_total += total
        status = "GOAL MET!" if total >= GOAL else f"missed  (-{GOAL - total})"
        if total >= GOAL:
            goal_days += 1
        role_str = " | ".join(f"{k.upper()}={roles.get(k, 0)}" for k in ROLES)
        print(f"  {date}  {total:3d}/{GOAL}  [{status}]  {role_str}")
        for r in ROLES:
            role_totals[r] += roles.get(r, 0)
    print(f"{'─'*70}")
    print(f"  Total applications  : {grand_total}")
    print(f"  Days tracked        : {len(log)}")
    print(f"  Days goal met       : {goal_days}")
    print(f"  Days goal missed    : {len(log) - goal_days}")
    print(f"\n  By Role:")
    for key, label in ROLES.items():
        print(f"    {label:<35}: {role_totals[key]}")
    print(f"{'='*70}\n")

# ─── Setup email ──────────────────────────────────────────────────────────────

def setup_email():
    print("\n=== Email Setup for Job Tracker ===")
    print("You need a Gmail App Password (NOT your regular Gmail password)")
    print("Steps:")
    print("  1. Go to myaccount.google.com > Security > 2-Step Verification (enable it)")
    print("  2. Go to myaccount.google.com > Security > App Passwords")
    print("  3. Create an app password for 'Mail'")
    print("  4. Copy the 16-character password\n")
    sender   = input("Your Gmail address (sender): ").strip()
    password = input("Gmail App Password (16 chars): ").strip()
    receiver = input("Receiver email [rajubaddela1234@gmail.com]: ").strip()
    if not receiver:
        receiver = "rajubaddela1234@gmail.com"
    groq_key = input("Groq API Key (leave blank to skip): ").strip()
    cfg = {"email_sender": sender, "email_password": password,
           "email_receiver": receiver, "groq_api_key": groq_key}
    with open(CONFIG, "w") as f:
        json.dump(cfg, f, indent=2)
    print(f"\nConfig saved to {CONFIG}")
    print("Now run: python resume_tracker.py schedule")

# ─── Setup Windows Task Scheduler ────────────────────────────────────────────

def setup_scheduler():
    python  = sys.executable
    script  = os.path.abspath(__file__)
    pythonw = python.replace("python.exe", "pythonw.exe")

    # Compute correct local task times for UK BST/GMT
    uk_now    = now_uk()
    local_now = datetime.now().astimezone()
    delta_h   = int((uk_now.utcoffset() - local_now.utcoffset()).total_seconds() / 3600)

    def uk_to_local(uk_hour):
        return f"{(uk_hour - delta_h) % 24:02d}:00"

    morning_t  = uk_to_local(7)
    midday_t   = uk_to_local(12)

    tr  = f'\\"{python}\\" \\"{script}\\"'
    tww = f'\\"{pythonw}\\" \\"{script}\\"'

    print(f"\n{'='*60}")
    print(f"  Setting up Windows Task Scheduler")
    print(f"  UK offset vs system: {delta_h:+d}h  (BST=+1, GMT=0)")
    print(f"  Morning task: {morning_t} system time = 07:00 UK")
    print(f"  Midday task : {midday_t} system time = 12:00 UK")
    print(f"{'='*60}\n")

    def register(name, sc_flags, arg, desc):
        cmd = f'schtasks /create /tn "{name}" /tr "{tr} {arg}" {sc_flags} /f'
        r   = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        tag = "[OK]  " if r.returncode == 0 else "[FAIL]"
        print(f"  {tag}  {desc}")
        if r.returncode != 0:
            print(f"         {r.stderr.strip()}")

    register("ResumeTracker_Morning_7AM",
             f"/sc daily /st {morning_t}", "morning",
             f"[{morning_t}] 7 AM UK motivation email")
    register("ResumeTracker_Midday_12PM",
             f"/sc daily /st {midday_t}", "midday",
             f"[{midday_t}] 12 PM UK progress email")

    watch_cmd = (
        f'schtasks /create /tn "ResumeTracker_Watcher" '
        f'/tr "{tww} watch" /sc onlogon /f'
    )
    r = subprocess.run(watch_cmd, shell=True, capture_output=True, text=True)
    tag = "[OK]  " if r.returncode == 0 else "[FAIL]"
    print(f"  {tag}  [Login] File watcher starts silently on login (checks every 30s)")
    if r.returncode != 0:
        print(f"         {r.stderr.strip()}")
        print(f"         Run this terminal as Administrator and try again.")

    print(f"\n  Drop any .docx resume file into: {SCAN_ROOT}")
    print(f"  It will be auto-classified and counted within 30 seconds.")
    print(f"{'='*60}\n")

# ─── LLM / Groq integration ──────────────────────────────────────────────────

def load_context():
    path = os.path.join(BASE, "context.json")
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {}

def get_day_context():
    now  = now_uk()
    wd   = now.weekday()   # 0=Mon … 6=Sun
    hour = now.hour
    on_shift = (
        (wd == 3 and hour >= 23) or
        (wd == 4 and hour < 11)  or
        (wd == 4 and hour >= 23) or
        (wd == 5 and hour < 11)
    )
    if on_shift:
        return (
            "Raju is currently ON his Amazon Associate night shift (Thu 11PM-Fri 11AM or Fri 11PM-Sat 11AM). "
            "He has very limited time. Even 5-10 quality applications is a great achievement today. "
            "Do NOT pressure him with the full 25-job goal — acknowledge his effort working night shifts while job hunting."
        )
    if wd == 5:
        return "It is Saturday. Recruiter activity is low on weekends — fewer responses expected. Encourage quality over quantity."
    if wd == 6:
        return "It is Sunday. Recruiter activity is very low. Encourage Raju to apply to a few high-quality roles and use time to refine resumes."
    return "Normal weekday — Raju should aim for the full 25 applications today."

def _build_gemini_profile():
    ctx = load_context()
    if not ctx:
        return ""
    p   = ctx.get("personal", {})
    ws  = ctx.get("work_schedule", {})
    jh  = ctx.get("job_hunt", {})
    res = ctx.get("resumes", {})

    role_skills = []
    for rkey in ("ai_engineer", "data_analyst", "data_scientist", "ml_engineer"):
        r = res.get(rkey, {})
        if r:
            skills_preview = " | ".join(r.get("skills", [])[:3])
            role_skills.append(f"  [{r.get('title', rkey)}]: {skills_preview}")

    projects = []
    seen = set()
    for rkey in ("ai_engineer", "ml_engineer", "data_scientist", "data_analyst"):
        for proj in res.get(rkey, {}).get("projects", []):
            name = proj.get("name", "")
            if name not in seen:
                seen.add(name)
                h = proj.get("highlights", [""])
                projects.append(f"  - {name}: {h[0]}")

    exp_lines = []
    seen_exp = set()
    for rkey in ("ai_engineer", "ml_engineer"):
        for e in res.get(rkey, {}).get("experience", []):
            key = e.get("company", "") + e.get("role", "")
            if key not in seen_exp:
                seen_exp.add(key)
                h = " | ".join(e.get("highlights", [])[:2])
                exp_lines.append(f"  - {e.get('company')} ({e.get('role')}, {e.get('period')}): {h}")

    certs = []
    for rkey in res:
        for c in res[rkey].get("certifications", []):
            if c not in certs:
                certs.append(c)

    return f"""=== BADDELA RAJU — FULL PROFILE ===
Personal : {p.get('name')}, {p.get('location')} | {p.get('email')} | {p.get('phone')}
Education: {p.get('education')}
Context  : {p.get('context', '')}

Target Roles: {' | '.join(jh.get('target_roles', []))}
Daily Goal  : {jh.get('daily_goal', 25)} applications/day

SKILLS BY ROLE:
{chr(10).join(role_skills)}

WORK EXPERIENCE:
{chr(10).join(exp_lines)}

NOTABLE PROJECTS (with real metrics):
{chr(10).join(projects[:8])}

CERTIFICATIONS: {', '.join(certs[:6])}

AMAZON SHIFT SCHEDULE:
  {' | '.join(ws.get('amazon_shifts', []))}
  Note: {ws.get('shift_note', '')}
"""

def _get_hunt_stats():
    """Compute rich job-hunt statistics to give the LLM full historical context."""
    log = load_log()
    if not log:
        return "No application history yet — this is Day 1."

    totals = []
    grand_total = 0
    role_totals = {r: 0 for r in ROLES}
    goal_days   = 0
    zero_days   = 0

    for date, entry in log.items():
        if isinstance(entry, int):
            t, roles = entry, {}
        else:
            t     = entry.get("total", 0)
            roles = entry.get("roles", {})
        totals.append((date, t))
        grand_total += t
        if t >= GOAL:
            goal_days += 1
        if t == 0:
            zero_days += 1
        for r in ROLES:
            role_totals[r] += roles.get(r, 0)

    totals.sort()
    days_tracked  = len(totals)
    best_date, best_count = max(totals, key=lambda x: x[1])
    avg           = grand_total / days_tracked if days_tracked else 0
    missed_days   = days_tracked - goal_days

    recent = totals[-7:]
    recent_str = " → ".join(f"{d[5:]}:{c}" for d, c in recent)

    # current streak (consecutive days with >0 apps, counting backward)
    streak = 0
    for _, c in reversed(totals):
        if c > 0:
            streak += 1
        else:
            break

    today_str = today()
    today_total = log.get(today_str, {})
    if isinstance(today_total, int):
        today_total = today_total
    else:
        today_total = today_total.get("total", 0)

    role_breakdown = " | ".join(f"{k.upper()}={role_totals[k]}" for k in ROLES)
    top_role       = max(role_totals, key=lambda r: role_totals[r])
    top_role_label = ROLES.get(top_role, top_role)

    return f"""
=== JOB HUNT STATS (all-time) ===
Total applications  : {grand_total} across {days_tracked} tracked days
Daily average       : {avg:.1f} apps/day (goal: {GOAL})
Best single day     : {best_date} — {best_count} applications
Goal days (>={GOAL}) : {goal_days} / {days_tracked} days ({int(goal_days/days_tracked*100) if days_tracked else 0}% hit rate)
Days missed (<{GOAL}) : {missed_days} ({zero_days} were zero-application days)
Current streak      : {streak} consecutive days with applications
Top role applied to : {top_role_label} ({role_totals[top_role]} total)
All-time by role    : {role_breakdown}
Last 7 days (MM-DD:apps): {recent_str}
"""

def generate_llm_content(email_type, applied, roles_data, remaining):
    cfg     = load_config()
    api_key = cfg.get("groq_api_key", "")
    if not api_key:
        return None

    try:
        from groq import Groq
        import re as _re
    except ImportError:
        return None

    day_note   = get_day_context()
    date_str   = today_display()
    profile    = _build_gemini_profile()
    stats      = _get_hunt_stats()
    uk_now     = now_uk()
    dow        = uk_now.strftime("%A")

    role_lines = "\n".join(
        f"  {label:<35}: {roles_data.get(key, 0)} applied today"
        for key, label in ROLES.items()
    )
    weakest_role  = min(roles_data, key=lambda r: roles_data.get(r, 0))
    weakest_label = ROLES.get(weakest_role, weakest_role)
    strongest_role  = max(roles_data, key=lambda r: roles_data.get(r, 0))
    strongest_label = ROLES.get(strongest_role, strongest_role)
    pace_projection = int(applied / uk_now.hour * 12) if uk_now.hour > 0 else 0

    context_block = f"""
=== TODAY ({date_str} — {dow}) ===
UK schedule context : {day_note}
Applications done   : {applied}/{GOAL}  ({remaining} remaining)
Today's role counts :
{role_lines}
Strongest role today: {strongest_label} ({roles_data.get(strongest_role, 0)})
Weakest role today  : {weakest_label} ({roles_data.get(weakest_role, 0)})
Pace projection     : ~{pace_projection} apps by end of day at current rate
"""

    # ── MORNING ──────────────────────────────────────────────────────────────
    if email_type == "morning":
        ms = _morning_stats()
        instruction = f"""You are Raju's elite personal job hunt coach. Write his 7 AM morning email — sharp, energising, specific. Not a diary. Not generic.

CONTEXT:
- Date: {date_str} ({dow})
- Yesterday: {ms['yesterday_total']} applications | This week: {ms['week_total']} | All-time: {ms['grand_total']}
- Streak: {ms['streak']} consecutive days with applications
- {ms['month_name']}: {ms['days_active']} days active | avg {ms['avg_per_day']}/day | goal hit {ms['goal_hit']} days
- Today's goal: {GOAL} applications across AI, DA, DS, ML, SE roles

RULES:
- Every word must feel written for TODAY specifically — reference the stats above.
- Name his real projects: LangGraph multi-agent pipeline, Agentic AI Video Synthesizer, QLoRA fine-tuning, RAG chatbot (87% accuracy), YOLOv8 defect detection, LSTM forecasting, KPMG Tableau dashboard, MLflow pipeline.
- Name real London sectors: fintech, healthtech, legaltech, defence tech, media AI, AI startups Series A-C.
- "motivation" = 2-3 punchy sentences. Open with something specific to his stats or streak. End with energy.
- "plan" = 2 concrete sentences: exact role order + one keyword tip for today.
- No filler. No "remember to". No "it is important". Active voice only.

Return ONLY valid JSON (no markdown, no code fences):
{{
  "headline": "5-7 word punchy headline specific to today — not generic",
  "motivation": "2-3 sentences energising and specific to his stats and skills — unique to {date_str}",
  "plan": "2 sentences: which role to start with and why, plus one concrete search keyword to use today"
}}"""

    # ── MIDDAY ───────────────────────────────────────────────────────────────
    elif email_type == "midday":
        if applied >= GOAL:
            tone_note = "celebratory — he hit the goal before noon, extraordinary discipline"
        elif applied >= 15:
            tone_note = "strong encouragement — excellent morning, afternoon will seal it"
        elif applied >= 8:
            tone_note = "constructive urgency — decent start, needs a focused afternoon push"
        elif applied >= 3:
            tone_note = "honest urgency — morning was slow, afternoon must be relentless"
        else:
            tone_note = "firm but caring alert — very few applications, needs an immediate reset (check Amazon shift context)"

        instruction = f"""You are Raju's elite job hunt coach delivering his 12 PM MIDDAY HALF-TIME BRIEFING.
Tone: {tone_note}

He has done {applied}/{GOAL} applications this morning. Role breakdown: {", ".join(f"{k.upper()}={roles_data.get(k,0)}" for k in ROLES)}.
Weakest role: {weakest_label} ({roles_data.get(weakest_role, 0)} apps). Strongest: {strongest_label} ({roles_data.get(strongest_role, 0)} apps).

RULES:
- Be specific about WHAT he achieved this morning (name the exact numbers per role).
- Give a real half-time performance verdict — not vague encouragement.
- The afternoon battle plan must be HOUR-BY-HOUR with specific role targets and search keywords.
- Reference his specific skills/projects when advising which type of company to hit this afternoon.
- Never repeat morning advice verbatim. This is a fresh tactical briefing based on where he actually stands.

Return ONLY valid JSON (no markdown, no extra text):
{{
  "headline": "honest half-time headline reflecting exact {applied}/{GOAL} — no emoji",
  "body": "5-6 sentences: name the exact morning numbers per role, give an honest verdict on pace vs goal, acknowledge what went well and what didn't, set the tone for the afternoon with real energy",
  "half_time_verdict": "3-4 sentences of cold honest analysis: is he on track for 25? What specific pattern do you see in his morning (e.g. 'You crushed AI roles but DA and DS are at zero — that imbalance will hurt your profile breadth')? Compare to what his best days look like from the stats. No sugarcoating.",
  "afternoon_battle_plan": "5-6 sentences: hour-by-hour plan from 1 PM to 6 PM UK. Assign specific role targets per hour (e.g. '1-2 PM: 6 ML Engineer roles — search MLOps fintech London, senior ML engineer Series B'). Name which of his projects to lead with per role type. Name 2-3 specific company types to prioritise this afternoon based on his skills.",
  "role_gap_fix": "2-3 sentences: focus on the weakest role ({weakest_label} at {roles_data.get(weakest_role, 0)}). Give 3 specific JD search phrases to find those roles fast. Explain exactly which of his skills/projects makes him strong for that role type.",
  "personal_edge": "2-3 sentences: name one specific technical advantage Raju has over other applicants in the London market right now — be precise (e.g. 'Very few London candidates can show production-level RAG with evaluated accuracy metrics AND a client-facing Tableau dashboard — you can. Lead with both this afternoon.')"
}}"""

    # ── CHECK ────────────────────────────────────────────────────────────────
    elif email_type == "check":
        if applied >= GOAL:
            tone_note = "proud celebration — goal smashed, encourage maintaining the streak tomorrow"
        elif applied >= 15:
            tone_note = "energetic push — almost there, one final sprint will close the gap"
        elif applied >= 8:
            tone_note = "urgent but supportive — real gap exists, needs focused action NOW"
        elif applied >= 1:
            tone_note = "direct wake-up call — too few apps for this time of day, respectful urgency"
        else:
            tone_note = "caring alarm — zero applications, check shift context, mobilise immediately"

        hour_str = uk_now.strftime("%I:%M %p")

        instruction = f"""You are Raju's elite job hunt coach sending a MID-DAY PROGRESS CHECK at {hour_str} UK time.
Tone: {tone_note}

Current: {applied}/{GOAL} done. Role breakdown: {", ".join(f"{k.upper()}={roles_data.get(k,0)}" for k in ROLES)}.
Pace projection based on hour: ~{pace_projection} apps by end of day at current rate.

RULES:
- Open with the EXACT numbers — no vague "you've made some progress".
- The momentum read must do real maths: at his current pace will he hit 25?
- The action sprint must name SPECIFIC search terms and SPECIFIC company types matching his skills.
- The role gap analysis must name the lagging role AND give 3 keyword phrases to fix it fast.
- Reference his history (from stats) to anchor the feedback — has he had better days? What did those look like?

Return ONLY valid JSON (no markdown, no extra text):
{{
  "headline": "precise progress headline with exact {applied}/{GOAL} count and time — no emoji",
  "body": "5-6 sentences: state exact role-by-role numbers, give honest assessment of pace, reference one insight from his historical stats (e.g. 'On your best day you hit 29 — today you need to beat your average of X'), connect urgency to his real goal (landing a job in London this year), close with one line that makes him want to open a new tab and apply",
  "momentum_read": "2-3 sentences of real maths: at {applied} apps by {hour_str}, he is projected to reach {pace_projection} by midnight. Is that enough? What exactly does he need to do in the next 2 hours to get back on track for {GOAL}? Give the specific number he needs per hour.",
  "action_sprint": "4-5 sentences: a precise 90-minute sprint plan — which role to open RIGHT NOW, which 3 JD keywords to search on LinkedIn/Indeed, which type of company to target (startup vs enterprise, which sector), how many applications to complete before the next check-in. Name one of his projects to copy-paste into the cover letter for maximum speed.",
  "role_gap_analysis": "2-3 sentences: {weakest_label} is at {roles_data.get(weakest_role, 0)} — give 3 SPECIFIC search phrases to find those roles fast (e.g. 'data scientist fintech London', 'NLP engineer AI startup', 'ML engineer Series B'). Explain in one line which of his specific skills makes him a strong candidate for that role type."
}}"""

    # ── MIDNIGHT ─────────────────────────────────────────────────────────────
    else:
        if applied >= GOAL:
            tone_note = "genuinely proud and celebratory — he hit or exceeded the goal, honour it"
        elif applied >= 18:
            tone_note = "positive and honest — strong day, just short, encourage tomorrow's push"
        elif applied >= 10:
            tone_note = "constructive and forward-looking — decent effort, real gap, clear tomorrow plan"
        elif applied >= 3:
            tone_note = "honest and direct — below expectations, name it clearly but rebuild positively"
        else:
            tone_note = "caring and reset-focused — very few or zero apps, check shift context, start fresh tomorrow"

        instruction = f"""You are Raju's elite job hunt coach delivering his MIDNIGHT END-OF-DAY DEBRIEF.
Tone: {tone_note}

Final count: {applied}/{GOAL}. Role breakdown: {", ".join(f"{k.upper()}={roles_data.get(k,0)}" for k in ROLES)}.
Weakest role: {weakest_label} ({roles_data.get(weakest_role, 0)}). Strongest: {strongest_label} ({roles_data.get(strongest_role, 0)}).

RULES:
- Use his full historical stats to give a data-driven verdict on today.
- Be honest about the number — {applied} is {applied}. Don't inflate it.
- The tomorrow battle plan must be hyper-specific: wake time, first role, target per role, search keywords for each.
- The skill weapon section must name ONE specific project and explain exactly how to use it tomorrow — not general advice.
- The mindset reset must leave him feeling capable and ready, not crushed or falsely inflated.
- Never repeat today's advice. This is a fresh strategic brief for tomorrow.

Return ONLY valid JSON (no markdown, no extra text):
{{
  "headline": "honest end-of-day headline for {applied}/{GOAL} — no emoji, no cliches",
  "body": "6-7 sentences: open with the exact number and honest context (e.g. 'Today ended at {applied} applications — {remaining} short of the {GOAL} target'); name the role breakdown specifically; reference one pattern from his historical stats (compare to average, best day, streak); acknowledge any extenuating factors (Amazon shift, weekend) if the context mentions them; be direct about what this means for his job hunt timeline; close with one forward-looking sentence that reframes tomorrow as a real opportunity",
  "day_verdict": "3-4 sentences of cold, clear analysis: what worked today (which roles got traction, what pace was achieved), what didn't work (which roles were ignored, where time was lost), one specific pattern you notice across his recent days from the stats. No sugarcoating — this is a coaching debrief, not a pep talk.",
  "performance_context": "2-3 sentences: how does {applied} compare to his all-time average, his best day, and his last 7 days? What does this tell him about his job hunt arc? Is he improving, plateauing, or declining? Give the honest read with specific numbers from his stats.",
  "tomorrow_battle_plan": "6-7 sentences of hyper-specific tomorrow plan: exact recommended wake time (e.g. '7:30 AM — open LinkedIn before breakfast'); role attack order with specific targets per role (e.g. 'First 8 AI Engineer roles by 9:30 AM — search LangChain engineer London, agentic AI startup, applied AI Series B'); 3 specific JD keyword phrases for each role type; which sectors to prioritise for each role; name the company size/stage most likely to respond to his profile; include one 'power move' (e.g. 'Send 3 personalised LinkedIn messages to AI team leads at Series B startups — your GitHub RAG project gives you a conversation starter')",
  "skill_weapon": "3-4 sentences: name ONE specific project from his CV that he should weaponise tomorrow — explain exactly which role type benefits, how to mention it (cover letter, LinkedIn summary, application note), why recruiters in that sector will immediately recognise its value, and what specific outcome/metric to highlight (e.g. '87% accuracy on domain-specific QA', '40% reduction in labelling costs with QLoRA', '95% defect detection with YOLOv8')",
  "mindset_reset": "2-3 sentences to close the day: acknowledge today honestly, then shift his mental frame to tomorrow — not with empty positivity but with a specific reason why tomorrow is a real opportunity (e.g. 'Monday morning recruiters are actively reviewing CVs — your RAG project puts you in the top 5% of AI applicants'). Leave him ready to sleep and wake up motivated."
}}"""

    prompt = (
        "You are Raju's elite personal AI job hunt coach. You have studied his full CV, all his projects, "
        "his Amazon shift schedule, and his complete application history. You give specific, data-driven, "
        "deeply personalised coaching — never generic advice.\n\n"
        f"{profile}\n{stats}\n{context_block}\n\n{instruction}"
    )

    try:
        client   = Groq(api_key=api_key)
        response = client.chat.completions.create(
            model       = "llama-3.3-70b-versatile",
            messages    = [{"role": "user", "content": prompt}],
            max_tokens  = 1400,
            temperature = 0.85,
        )
        text  = response.choices[0].message.content.strip()
        match = _re.search(r'\{[\s\S]*\}', text)
        if match:
            return json.loads(match.group())
    except Exception as e:
        print(f"Groq error: {e}")

    return None

# ─── Background file watcher ─────────────────────────────────────────────────

def watch_folder(interval=30):
    """Polls every `interval` seconds; scans instantly when new .docx is detected in SCAN_ROOT."""
    log_path = os.path.join(BASE, "watcher.log")

    def log(msg):
        line = f"[{now_uk().strftime('%Y-%m-%d %H:%M:%S')} UK] {msg}"
        with open(log_path, "a") as f:
            f.write(line + "\n")

    log(f"Watcher started — polling every {interval}s in {SCAN_ROOT}")

    def get_snapshot():
        snap = {}
        for root, dirs, files in os.walk(SCAN_ROOT):
            dirs[:] = [
                d for d in dirs
                if not d.startswith('.')
                and os.path.normcase(os.path.abspath(os.path.join(root, d))) !=
                   os.path.normcase(os.path.abspath(BASE))
            ]
            for fname in files:
                if fname.lower().endswith('.docx'):
                    fpath = os.path.join(root, fname)
                    snap[fpath] = os.path.getmtime(fpath)
        return snap

    known = get_snapshot()
    log(f"Snapshot: {len(known)} existing .docx files")

    while True:
        time.sleep(interval)
        try:
            current   = get_snapshot()
            new_files = [p for p in current if p not in known]
            if new_files:
                log(f"Detected {len(new_files)} new file(s): {[os.path.basename(p) for p in new_files]}")
                results = scan_and_log()
                log(f"Scan complete — {len(results)} new applications logged")
            known = current
        except Exception as e:
            log(f"Error: {e}")

# ─── CLI ──────────────────────────────────────────────────────────────────────

def print_help():
    print(f"""
Job Application Tracker — Commands:
  python resume_tracker.py morning          Send 7 AM UK motivation email
  python resume_tracker.py midday           Send 12 PM UK progress check email
  python resume_tracker.py midnight         Send midnight UK final summary
  python resume_tracker.py scan             Auto-classify all .docx files and log them
                                             (Scans: {SCAN_ROOT})
  python resume_tracker.py add <role> [n]   Log n applications (default 1)
                                             Roles: ai, da, ds, ml, se
  python resume_tracker.py check            Manual check + notification
  python resume_tracker.py summary          Show full history
  python resume_tracker.py setup            Configure email (run once)
  python resume_tracker.py schedule         Register Windows scheduled tasks (UK time)

Examples:
  python resume_tracker.py morning          (7 AM UK motivation — unique each day)
  python resume_tracker.py add ai 5         (log 5 AI Engineer applications)
  python resume_tracker.py add se 2         (log 2 Software Engineer applications)
  python resume_tracker.py midday           (see how many done by noon UK time)
""")

if __name__ == "__main__":
    args = sys.argv[1:]
    if not args or args[0] == "check":
        check_and_notify()
    elif args[0] == "morning":
        morning_motivate()
    elif args[0] == "midday":
        midday_check()
    elif args[0] == "midnight":
        midnight_summary()
    elif args[0] == "add":
        if len(args) < 2:
            print("Usage: python resume_tracker.py add <role> [n]")
            print("Roles:", ", ".join(ROLES.keys()))
        else:
            role = args[1].lower()
            n    = int(args[2]) if len(args) > 2 else 1
            if role not in ROLES:
                print(f"Unknown role '{role}'. Valid: {', '.join(ROLES.keys())}")
            else:
                entry = add_application(role, n)
                total = entry["total"]
                print(f"Logged {n}x {ROLES[role]}. Today: {total}/{GOAL}")
                auto_push_log()
                if total >= GOAL:
                    toast("GOAL ACHIEVED!", f"{total}/{GOAL} jobs applied today! YOU DID IT!")
                else:
                    toast(f"{total}/{GOAL} Jobs Applied", f"{GOAL - total} more to go today! Keep pushing!")
    elif args[0] == "scan":
        scan_and_log()
    elif args[0] == "watch":
        watch_folder()
    elif args[0] == "summary":
        show_summary()
    elif args[0] == "setup":
        setup_email()
    elif args[0] == "schedule":
        setup_scheduler()
    else:
        print_help()
